import "@/style/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";

export const metadata: Metadata = {
	title: "TweetBounty",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
