import "@/style/globals.css";
import type { Metadata } from "next";
import React from "react";
import { Providers } from "@/Providers";

export const metadata: Metadata = {
	title: "TweetBounty",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
